export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';
export const MAKE_FAVORITE_PHOTO = 'MAKE_FAVORITE_PHOTO';
export const FETCH_LOCAL_PHOTOS = 'FETCH_LOCAL_PHOTOS';
